# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/master/LICENSE ).
[workspace]

members = [
    "components/cldr_json_data_provider",
    "components/data_provider",
    "components/datetime",
    "components/ecma402",
    "components/fs_data_provider",
    "components/icu",
    "components/icu4x",
    "components/locid",
    "components/locid/macros",
    "components/plurals",
    "components/uniset",
    "resources/testdata",
    "utils/fixed_decimal",
]
