# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/master/LICENSE ).
[package]
name = "icu"
description = "International Components for Unicode"
version = "0.0.1"
authors = ["The ICU4X Project Developers"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/unicode-org/icu4x"
license-file = "../../LICENSE"
categories = ["internationalization"]
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md"
]

[dependencies]
icu_datetime = { path = "../datetime" }
icu_locid = { path = "../locid" }
icu_locid_macros = { path = "../locid/macros" }
icu_plurals = { path = "../plurals" }
icu_uniset = { path = "../uniset" }

[dev-dependencies]
icu_testdata = { path = "../../resources/testdata" }
